 FROM public.ecr.aws/lambda/python:3.10

COPY requirements-lambda.txt .
RUN pip install --no-cache-dir -r requirements-lambda.txt --target ${LAMBDA_TASK_ROOT}

COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY src ${LAMBDA_TASK_ROOT}/src

CMD ["lambda_function.lambda_handler"]